### ISSUE TITLE
plot_dist() for many input features requires massive plot - please add limit for N most important features

### ISSUE THREAD

**Issue by mdhimes** [edahelsinki/pyslise#11]
Hi,

I'm currently testing out pyslise for a model with many input features (>1000).  When using plot_dist() to view the explanation for a given test case, it attempts to plot every feature, which requires making a massive figure in order resolve each feature in the plots.  It's generally unwieldy to work with, and presumably not what the devs intended.

Given that the features are already plotted in order of importance, I would suggest adding an option to this function that limits the plot to the N most important features, or better yet, pass in an array of indices that the user wants to plot.  This way, one could break up a problem with 1000 inputs into 40 groups of 25 or something more manageable.

**Comment by Aggrathon** [comment]
That's not a bad idea, and pretty simple to implement as well!

(Although I'm a bit sceptical to how interpretable a linear model with >1000 variables really is, but you know your dataset better than me...)

**Comment by Aggrathon** [comment]
I've created a new version (do a `pip --upgrade slise`) that adds a new argument to `plot_dist` for specifying which variables to plot. Use e.g. `plot_dist(order=[4, 2, 5, 12, 24])` or `plot_dist(order=range(10, 20))`  to choose the order and selection of variables or `plot_dist(order=10)` for 10 variables with largest absolute coefficients.

**Comment by mdhimes** [comment]
Thanks for the quick update!  Works perfectly.
